(() => {
  const $ = id => document.getElementById(id);
  const DEFAULT_RECIPIENT = '공군 제5공중기동비행단 재무관 귀하';
  const DEFAULT_COMMANDER = '제5공중기동비행단장';
  const DEFAULT_LOCATION = 'K-1';
  const DEFAULT_MEETING_PLACE = '기술관리실 회의실';
  const DEFAULT_EDUCATION_CONTENT = '안전 교육 및 안전위해요소 확인 등';
  const v = id => ($(id)?.value ?? '').trim();
  const parseAmount = s => { const x=String(s||'').replace(/[^\d-]/g,''); return (!x||x==='-')?'':Number(x); };
  const money = s => { const n=parseAmount(s); return n===''?'':`${n.toLocaleString('ko-KR')}원`; };
  const amountText = s => { const n=parseAmount(s); return n===''?'':n.toLocaleString('ko-KR'); };
  const dateKo = s => { if(!s)return ''; const [y,m,d]=s.split('-').map(Number); return `${y}년 ${m}월 ${d}일`; };
  const dateKoOrBlank = s => dateKo(s) || '년     월      일';
  const dateShort = s => { if(!s)return ''; const [y,m,d]=s.split('-').map(Number); return `${String(y).slice(-2)}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`; };
  const subtractWeekdays = (s,days) => { if(!s)return ''; const [y,m,d]=s.split('-').map(Number), dt=new Date(y,m-1,d); let left=days; while(left>0){dt.setDate(dt.getDate()-1);const day=dt.getDay();if(day!==0&&day!==6)left--;} return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`; };
  const clone = x => JSON.parse(JSON.stringify(x));

  function buildBaseWorkbook() {
    if (typeof ExcelJS === 'undefined') throw new Error('엑셀 생성 모듈을 불러오지 못했어. 인터넷 연결을 확인한 뒤 새로고침해줘.');
    if (!window.WORKBOOK_SCHEMA) throw new Error('workbook-schema.js를 불러오지 못했어. 모든 파일을 같은 폴더에 두어야 해.');
    const wb = new ExcelJS.Workbook(); wb.creator='준공서류 자동 생성기'; wb.created=new Date();
    const schema=window.WORKBOOK_SCHEMA;
    for(const spec of schema.sheets){
      const ws=wb.addWorksheet(spec.name,{views:spec.views||[]});
      for(const c of spec.columns) for(let i=c.min;i<=c.max;i++){const col=ws.getColumn(i);col.width=c.width;col.hidden=!!c.hidden;col.outlineLevel=c.outlineLevel||0;}
      for(const r of spec.rows){const row=ws.getRow(r.number);if(r.height!=null)row.height=r.height;row.hidden=!!r.hidden;row.outlineLevel=r.outlineLevel||0;}
      for(const m of spec.merges) ws.mergeCells(m);
      for(const c of spec.cells){const cell=ws.getCell(c.address);if(c.formula!=null)cell.value={formula:c.formula};else if('value'in c)cell.value=c.value;const st=schema.styles[c.style]||{};if(st.font)cell.font=clone(st.font);if(st.fill)cell.fill=clone(st.fill);if(st.border)cell.border=clone(st.border);if(st.alignment)cell.alignment={...clone(st.alignment),vertical:'middle'};if(st.numFmt)cell.numFmt=st.numFmt;if(st.protection)cell.protection=clone(st.protection);}
      ws.pageSetup={...ws.pageSetup,...(spec.pageSetup||{})}; ws.pageMargins=spec.pageMargins||ws.pageMargins;
    }
    return wb;
  }
  function set(ws,addr,value,align){const cell=ws.getCell(addr);cell.value=value??'';cell.font={...(cell.font||{}),color:{argb:'FF000000'}};cell.alignment={...(cell.alignment||{}),vertical:'middle',...(align||{})};}
  function overviewText(){return [...document.querySelectorAll('.overview-input')].map(x=>x.value.trim()).filter(Boolean).map(x=>x.startsWith('ㅁ')?x:`ㅁ ${x}`).join('\n\n');}
  function workerData(){return [...document.querySelectorAll('.worker-row')].map(row=>({position:(row.querySelector('.worker-position')?.value||'').trim(),name:(row.querySelector('.worker-name')?.value||'').trim()})).filter(x=>x.position||x.name);}
  function data(){
    const contractRaw=v('contractAmount'), completionRaw=v('completionAmount');
    const contractNum=parseAmount(contractRaw), completionNum=parseAmount(completionRaw);
    return {projectName:v('projectName'),companyName:v('companyName'),constructionUnit:v('constructionUnit')||'제5공중기동비행단',commander:v('commander')||DEFAULT_COMMANDER,location:v('location')||DEFAULT_LOCATION,contractAmount:money(contractRaw),contractAmountText:amountText(contractRaw),changedAmount:money(v('changedAmount')),materialAmount:money(v('materialAmount')),completionAmountText:amountText(completionRaw),settlementText:(contractNum!==''&&completionNum!=='')?(contractNum-completionNum).toLocaleString('ko-KR'):'',contractDate:dateKo(v('contractDate')),completionDate:dateKo(v('completionDate')),inspectionDate:dateKo(v('inspectionDate')),approvalDate:dateKo(v('approvalDate')),approvalNumber:v('approvalNumber'),actualStartDateRaw:v('actualStartDate'),actualStartDate:dateKo(v('actualStartDate')),actualCompletionDate:dateKo(v('actualCompletionDate')),bidDate:dateKoOrBlank(v('bidDate')),extensionDate:dateKoOrBlank(v('extensionDate')),designerPosition:v('designerPosition'),designerName:v('designerName'),supervisorRank:v('supervisorRank'),supervisorName:v('supervisorName'),constructorPosition:v('constructorPosition'),constructorName:v('constructorName'),inspectorRank:v('inspectorRank'),inspectorName:v('inspectorName'),attendeeAffiliation:v('attendeeAffiliation'),attendeePosition:v('attendeePosition'),attendeeRank:v('attendeeRank'),attendeeName:v('attendeeName'),attendeeOpinion:v('attendeeOpinion'),unitOpinion:v('unitOpinion'),overview:overviewText(),inspectionItem:v('inspectionItem'),inspectorComment:v('inspectorComment'),recipient:v('recipient')||DEFAULT_RECIPIENT,meetingPlace:v('meetingPlace')||DEFAULT_MEETING_PLACE,educationContent:v('educationContent')||DEFAULT_EDUCATION_CONTENT,battalionCommanderName:v('battalionCommanderName'),workers:workerData()};
  }
  function fillRecord(ws,d){set(ws,'C4',d.projectName);set(ws,'G6',d.completionDate?`${d.completionDate} 준공`:'',{horizontal:'left'});set(ws,'G7',d.contractDate,{horizontal:'left'});set(ws,'K7',d.companyName,{horizontal:'center'});set(ws,'I8',d.contractAmount);set(ws,'F10',d.completionDate?`${d.completionDate} 준공`:'');set(ws,'H19',d.inspectionDate,{horizontal:'right'});set(ws,'K20',d.inspectorRank);set(ws,'L20',d.inspectorName);set(ws,'M20','(인)');set(ws,'A24',d.recipient,{horizontal:'center'});}
  function fillResult(ws,d){set(ws,'B2',d.projectName);set(ws,'H2',d.approvalDate);set(ws,'H3',d.approvalNumber);set(ws,'B4',d.changedAmount);set(ws,'I4',d.contractAmount);set(ws,'I5',d.materialAmount);set(ws,'B6',d.overview);set(ws,'B11',d.designerPosition);set(ws,'C11',d.designerName);set(ws,'B17',d.supervisorRank);set(ws,'C17',d.supervisorName);set(ws,'B23',d.constructorPosition);set(ws,'C23',d.constructorName);set(ws,'B29',d.inspectorRank);set(ws,'C29',d.inspectorName);set(ws,'B35',d.inspectionDate);set(ws,'B41',d.inspectionItem);set(ws,'B45',d.inspectorComment);}
  function fillSupervisorReport(ws,d){set(ws,'C4',d.projectName);set(ws,'G7',d.contractDate);set(ws,'K7',d.companyName);set(ws,'F10',d.actualStartDate);set(ws,'K10',d.actualCompletionDate);set(ws,'K18',d.completionDate);set(ws,'K20',d.supervisorRank);set(ws,'L20',d.supervisorName);}
  function fillAttendeeOpinion(ws,d){set(ws,'C4',d.projectName);set(ws,'G10',d.inspectionDate);set(ws,'B13',d.attendeeOpinion,{horizontal:'left',wrapText:true});set(ws,'K17',d.inspectionDate);set(ws,'L19',d.attendeeAffiliation);set(ws,'L20',d.attendeePosition);set(ws,'L21',d.attendeeRank);set(ws,'L22',d.attendeeName);}
  function fillCompletionReport(ws,d){set(ws,'A2',d.completionDate);set(ws,'C3',d.constructionUnit);set(ws,'I3',d.commander);set(ws,'C4',d.projectName);set(ws,'I4',d.approvalDate);set(ws,'C5',d.approvalNumber);set(ws,'I5',d.location);set(ws,'J6',d.contractAmountText?`${d.contractAmountText} 원`:'');set(ws,'J7',d.completionAmountText?`${d.completionAmountText} 원`:'');set(ws,'J8',d.settlementText?`${d.settlementText} 원`:'');set(ws,'C9',d.constructorPosition,{horizontal:'center'});set(ws,'D9',d.constructorName);set(ws,'I9',d.supervisorRank,{horizontal:'center'});set(ws,'J9',d.supervisorName);set(ws,'C10',d.inspectorRank,{horizontal:'center'});set(ws,'D10',d.inspectorName);set(ws,'C11',d.bidDate);set(ws,'C16',d.contractDate);set(ws,'C21',d.actualStartDate);set(ws,'C26',d.completionDate);set(ws,'C31',d.extensionDate);set(ws,'H11',d.overview,{horizontal:'left',wrapText:true});set(ws,'C36',d.actualStartDate);set(ws,'C37',d.actualCompletionDate);set(ws,'C41',d.unitOpinion,{horizontal:'left',wrapText:true});}
  function fillWorkers(ws,d){const maxWorkers=17;if(d.workers.length>maxWorkers)throw new Error(`공사인부는 현재 양식상 최대 ${maxWorkers}명까지 입력할 수 있어.`);d.workers.forEach((worker,index)=>{const row=10+(index*2);set(ws,`A${row}`,index+1);set(ws,`B${row}`,d.companyName);set(ws,`C${row}`,worker.position);set(ws,`D${row}`,worker.name);});}
  function fillSafetyPledge(ws,d){set(ws,'G37',d.actualStartDate,{horizontal:'right'});set(ws,'H38',d.companyName);set(ws,'H39',d.constructorName);set(ws,'B41',`공군 ${d.constructionUnit} 귀하`,{horizontal:'center'});}
  function fillSafetyCouncil(ws,d){set(ws,'B5',d.meetingPlace);set(ws,'B6',d.projectName);fillWorkers(ws,d);}
  function fillSafetyEducation(ws,d){set(ws,'A1','안전교육 및 작업장 점검 결과',{horizontal:'center'});set(ws,'B4',d.meetingPlace);set(ws,'B5',d.projectName);set(ws,'B6',[d.supervisorRank,d.supervisorName].filter(Boolean).join(' '));set(ws,'B7',d.educationContent);fillWorkers(ws,d);}
  function fillRiskAssessment(ws,d){const evaluationDate=dateShort(subtractWeekdays(d.actualStartDateRaw,3));const improvementDate=dateShort(subtractWeekdays(d.actualStartDateRaw,2));set(ws,'J7',d.constructorName);set(ws,'M7',d.battalionCommanderName);set(ws,'B8',d.projectName);set(ws,'M8',evaluationDate);set(ws,'A12',d.projectName,{wrapText:true});for(const row of [12,13,14]){set(ws,`L${row}`,improvementDate);set(ws,`M${row}`,improvementDate);set(ws,`N${row}`,d.constructorName);}}
  function addSide(cell,side,style='medium'){cell.border={...(cell.border||{}),[side]:{style,color:{argb:'FF000000'}}};}
  function applyOuterBorder(ws,range,style='medium'){const m=/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/.exec(range);if(!m)return;const start=ws.getCell(`${m[1]}${m[2]}`),end=ws.getCell(`${m[3]}${m[4]}`);for(let c=start.col;c<=end.col;c++){addSide(ws.getCell(start.row,c),'top',style);addSide(ws.getCell(end.row,c),'bottom',style);}for(let r=start.row;r<=end.row;r++){addSide(ws.getCell(r,start.col),'left',style);addSide(ws.getCell(r,end.col),'right',style);}}
  function applyAllThinBorders(ws,range){const m=/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/.exec(range);if(!m)return;const start=ws.getCell(`${m[1]}${m[2]}`),end=ws.getCell(`${m[3]}${m[4]}`),side={style:'thin',color:{argb:'FF000000'}};for(let r=start.row;r<=end.row;r++)for(let c=start.col;c<=end.col;c++){const cell=ws.getCell(r,c);cell.border={...(cell.border||{}),left:{...side},right:{...side},top:{...side},bottom:{...side}};}}
  function clearSide(cell,side){const border={...(cell.border||{})};delete border[side];cell.border=border;}
  function styleCompletionHeaderBorder(ws){for(let c=1;c<=11;c++){clearSide(ws.getCell(1,c),'top');clearSide(ws.getCell(2,c),'bottom');addSide(ws.getCell(2,c),'bottom','medium');}for(let r=1;r<=2;r++){clearSide(ws.getCell(r,1),'left');clearSide(ws.getCell(r,11),'right');}}
  function applyScoreDiagonals(ws){for(const address of ['H16','I16','J16','H21','I21','J21','H26','I26','J26','H31','I31','J31','H36','I36','J36']){const cell=ws.getCell(address);cell.border={...(cell.border||{}),diagonal:{up:true,down:false,style:'thin',color:{argb:'FF000000'}}};cell.font={...(cell.font||{}),color:{argb:'FF000000'}};}for(let row=35;row<=40;row++)addSide(ws.getCell(row,1),'right','thin');}
  function applyMiddle(ws){ws.eachRow({includeEmpty:true},row=>row.eachCell({includeEmpty:true},cell=>cell.alignment={...(cell.alignment||{}),vertical:'middle'}));}
  function finalizeWorkbook(wb){const configs=[['준공검사조서','A1:N25',true],['준공검사 결과보고서','A1:J47',true],['용역감독관 준공 감독조서','A1:N25',true],['입회관 의견서','A1:N25',true],['용역 완결 보고서','A1:K45',true],['안전 보건 이행 확약서','A1:J43',false],['안전 보건 협의체 운영내용','A1:E43',false],['안전교육 및 작업장 점검 결과','A1:E43',false],['위험성 평가표','A1:N14',false]];for(const [name,area,useOuterBorder] of configs){const ws=wb.getWorksheet(name);if(!ws)continue;applyMiddle(ws);ws.pageSetup={...(ws.pageSetup||{}),printArea:area,fitToPage:true,fitToWidth:1,fitToHeight:1};if(useOuterBorder)applyOuterBorder(ws,area,'medium');}const record=wb.getWorksheet('준공검사조서');if(record)record.getCell('A2').font={...(record.getCell('A2').font||{}),underline:true};const result=wb.getWorksheet('준공검사 결과보고서');if(result)applyScoreDiagonals(result);const completion=wb.getWorksheet('용역 완결 보고서');if(completion)styleCompletionHeaderBorder(completion);const risk=wb.getWorksheet('위험성 평가표');if(risk){applyAllThinBorders(risk,'A8:N14');addSide(risk.getCell('H7'),'left','thin');}}
  function addOverview(initial=''){const row=document.createElement('div');row.className='overview-row';const inp=document.createElement('input');inp.className='overview-input';inp.placeholder='공사개요 항목';inp.value=initial;const btn=document.createElement('button');btn.type='button';btn.className='ghost';btn.textContent='삭제';btn.onclick=()=>document.querySelectorAll('.overview-row').length>1?row.remove():inp.value='';row.append(inp,btn);$('overviewList').append(row);}
  function renumberWorkers(){document.querySelectorAll('.worker-row').forEach((row,index)=>row.querySelector('.worker-no').textContent=index+1);}
  function addWorker(position='',name=''){const row=document.createElement('div');row.className='worker-row';const no=document.createElement('div');no.className='worker-no';const positionLabel=document.createElement('label');positionLabel.textContent='직급';const positionInput=document.createElement('input');positionInput.className='worker-position';positionInput.value=position;positionInput.placeholder='예: 반장';positionLabel.append(positionInput);const nameLabel=document.createElement('label');nameLabel.textContent='이름';const nameInput=document.createElement('input');nameInput.className='worker-name';nameInput.value=name;nameInput.placeholder='이름';nameLabel.append(nameInput);const btn=document.createElement('button');btn.type='button';btn.className='ghost';btn.textContent='삭제';btn.onclick=()=>{if(document.querySelectorAll('.worker-row').length>1){row.remove();renumberWorkers();}else{positionInput.value='';nameInput.value='';}};row.append(no,positionLabel,nameLabel,btn);$('workerList').append(row);renumberWorkers();}
  $('addOverview').onclick=()=>addOverview();
  $('addWorker').onclick=()=>addWorker();
  $('form').onsubmit=async e=>{e.preventDefault();const status=$('status');try{const defs=[['includeRecord','준공검사조서',fillRecord],['includeResult','준공검사 결과보고서',fillResult],['includeSupervisorReport','용역감독관 준공 감독조서',fillSupervisorReport],['includeAttendeeOpinion','입회관 의견서',fillAttendeeOpinion],['includeCompletionReport','용역 완결 보고서',fillCompletionReport],['includeSafetyPledge','안전 보건 이행 확약서',fillSafetyPledge],['includeSafetyCouncil','안전 보건 협의체 운영내용',fillSafetyCouncil],['includeSafetyEducation','안전교육 및 작업장 점검 결과',fillSafetyEducation],['includeRiskAssessment','위험성 평가표',fillRiskAssessment]];if(!defs.some(([id])=>$(id).checked))throw new Error('생성할 서류를 하나 이상 선택해줘.');status.textContent='선택한 9종 양식을 코드로 생성하는 중…';const wb=buildBaseWorkbook(),d=data();for(const [id,name,fill] of defs){const ws=wb.getWorksheet(name);if($(id).checked)fill(ws,d);else if(ws)wb.removeWorksheet(ws.id);}finalizeWorkbook(wb);const buf=await wb.xlsx.writeBuffer();const blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${d.projectName.replace(/[\\/:*?"<>|]/g,'_')||'준공서류'}_준공서류.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);status.textContent='완료! 선택한 준공서류를 생성했어.';}catch(err){console.error(err);status.textContent=err.message;}};
  $('sampleBtn').onclick=()=>{const vals={projectName:'전력설비 개선공사',companyName:'대한전기 주식회사',constructionUnit:'시설대대',commander:'제5공중기동비행단장',location:'K-1',contractAmount:'125000000',changedAmount:'130000000',materialAmount:'5000000',completionAmount:'124500000',contractDate:'2026-06-01',actualStartDate:'2026-06-03',completionDate:'2026-06-19',actualCompletionDate:'2026-06-18',inspectionDate:'2026-06-20',approvalDate:'2026-06-02',approvalNumber:'제2026-15호',bidDate:'2026-05-20',designerPosition:'설계담당',designerName:'홍길동',supervisorRank:'6급',supervisorName:'김감독',constructorPosition:'현장대리인',constructorName:'이시공',inspectorRank:'5급',inspectorName:'박검사',attendeeAffiliation:'시설대대',attendeePosition:'전기담당',attendeeRank:'7급',attendeeName:'최입회',attendeeOpinion:'준공검사 입회 결과 특이사항 없음.',unitOpinion:'공사 목적에 맞게 양호하게 시공되었음.',meetingPlace:DEFAULT_MEETING_PLACE,educationContent:DEFAULT_EDUCATION_CONTENT,battalionCommanderName:'홍대대'};for(const [k,val]of Object.entries(vals))if($(k))$(k).value=val;document.querySelectorAll('.overview-row').forEach(x=>x.remove());addOverview('수배전반 교체 1식');addOverview('전력케이블 포설 1식');document.querySelectorAll('.worker-row').forEach(x=>x.remove());addWorker('반장','김반장');addWorker('전공','이전공');};
  $('form').onreset=()=>setTimeout(()=>{document.querySelectorAll('.overview-row').forEach(x=>x.remove());addOverview();document.querySelectorAll('.worker-row').forEach(x=>x.remove());addWorker();$('recipient').value=DEFAULT_RECIPIENT;$('commander').value=DEFAULT_COMMANDER;$('location').value=DEFAULT_LOCATION;$('meetingPlace').value=DEFAULT_MEETING_PLACE;$('educationContent').value=DEFAULT_EDUCATION_CONTENT;$('battalionCommanderName').value='';$('inspectionItem').value='ㅇ 양  호';$('status').textContent='';});addOverview();addWorker();
})();